--- 
title: "My Economics Reading List"
author: "Michael DeWitt"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Prerequisites

## Philosophy

## Politics

* **An Introduction to Political Philosophy** by Jonathan Wolff
* **Veto Players: How Political Institutions Work** by George Tsebelis
* **Unifying Political Methodology: The Likelihood Theory of Statistical Inference** by Gary King
* **World Politics: Interests, Interactions, Institutions (Third Edition)** by by Jeffry A. Frieden, David A. Lake
* **The Disappearing Center: Engaged Citizens, Polarization, and American Democracy** by Alan I. Abramowitz

## Economics

* **Economics Facts and Fallacies** by Thomas Sowell
* **Why Nations Fail: The Origins of Power, Prosperity, and Poverty** by Daron Acemoglu, James A. Robinson
* **Microeconomics and Behavior** by Robert H. Frank
* **Microeconomics** by Jeffrey M. Perloff
* **Basic Economics** by Thomas Sowell
* **Applied Economics: Thinking Beyond Stage One** Thomas Sowell
* **Applied Econometrics with R** by Christian Kleiber, Achim Zeileis
* **Debt** by David Graeber
* **Capital in the Twenty-First Century** by Thomas Piketty

## Survey Methodology and Theory

* **Small Area Estimation (Wiley Series in Survey Methodology)** by J. N. K. Rao, Isabel Molina